// Shared types and interfaces for Party Games
// Constants
export const GAME_CONFIG = {
  LOBBY_CODE_LENGTH: 6,
  MIN_PLAYERS_TO_START: 3,
  MAX_LOBBY_IDLE_TIME: 30 * 60 * 1000, // 30 minutes
  HEARTBEAT_INTERVAL: 30 * 1000, // 30 seconds
  ROUND_COUNTDOWN_DURATION: 3, // seconds
};
export const ERROR_CODES = {
  LOBBY_NOT_FOUND: 'LOBBY_NOT_FOUND',
  LOBBY_FULL: 'LOBBY_FULL',
  GAME_IN_PROGRESS: 'GAME_IN_PROGRESS',
  NOT_HOST: 'NOT_HOST',
  PLAYER_NOT_FOUND: 'PLAYER_NOT_FOUND',
  INVALID_GAME_TYPE: 'INVALID_GAME_TYPE',
  NOT_ENOUGH_PLAYERS: 'NOT_ENOUGH_PLAYERS',
  ALREADY_IN_LOBBY: 'ALREADY_IN_LOBBY',
};
//# sourceMappingURL=index.js.map
